---
title: "Correlation exploration WF EV"
author: "Sarah Klain"
date: "May 1, 2016"
output: 
  html_document: 
    keep_md: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Setup

```{r}
library(Hmisc) #to run correlations with sig levels
library(ggthemes) # for pretty themes in ggplot
library(viridis) # for pretty colors
library(dplyr)
library(knitr) # tool for making nice tables
library(tidyr) # data table wrangling tool
library(broom)
library(stargazer) # makes pretty tables
library(corrgram)
library(ggplot2) # for great charts
# library(stats) # for PCA
# library(psych)
```

Input data

In cer_2016_01_08_dem4.csv I recoded const_st by removing the 5s, which removes the "not sure" responses
```{r}
setwd("/Users/sarahklain/Documents/R_2015/navi") #set working directory
ev_wf <- read.csv("cer_2016_01_08_dem4.csv")
#str(ev_wf)

```

### Correlations

```{r}
corr1 <- rcorr(as.matrix(ev_wf[11:37]), type = "pearson")
corr1

# corr2 <- rcorr(as.matrix(ev_wf[11:37]), type = "spearman")
# corr2
```

Make it visual

```{r}

corrgram(ev_wf[1:36], order=TRUE, lower.panel=panel.shade, 
   upper.panel=panel.pie, text.panel=panel.txt, main="Environmental Values & Wind Farm (PC2/PC1 Order)")

#fun colors
cg_yb <- corrgram(ev_wf[11:36], order=TRUE, lower.panel=panel.shade, 
   upper.panel=panel.pie, text.panel=panel.txt, col.regions = colorRampPalette(c("purple4", "skyblue1", "khaki1", "gold1")), main="Environmental Values & Wind Farm (PC2/PC1 Order)")

cg_yb
#ggsave(cg_yb, file = "/Users/sarahklain/Documents/R_2015/navi/corr_figs/cg_y_b.pdf")
#pdf(file = "/Users/sarahklain/Documents/R_2015/navi/corr_figs/cg_y_b.pdf")
```

```{r}
library(corrplot)
ev_wf2 <-na.omit(ev_wf)
cp1 <- corrplot(cor(as.matrix(ev_wf2[1:36])), order = "hclust", tl.col='black', tl.cex=.75, na.label.col = "black") 

cp1

cp2 <- corrplot(cor(as.matrix(ev_wf2[1:41])), order = "hclust", tl.col='black', tl.cex=.75, na.label.col = "black") 

cp2

corr <- cor((as.matrix(ev_wf2[12:25])))
corrplot(corr, method = "number", tl.cex = 1, tl.col='black')
```

get p values for smaller subset of variables
```{r}
library(psych)
corr.test(ev_wf[11:15], ev_wf[11:15])
corr.test(ev_wf[11:15], ev_wf[38:41])
corr.test(ev_wf[11:15], ev_wf[16:41])
```

oper negatively correlates with other_rel, 
const_st neg corr with clean instr

